import type { ITheme } from "../ITheme";

export const AquaTheme: ITheme = {
  name: "aqua",
  bodyColor: "#e6faff",
  backgroundColor: "#dbf9ff",
  textColor: "#1a3a3a",
  altTextColor: "#4a7c7c",
  highlightColor: "#52a6a6",
  borderColor: "#a3d6d6",
  borderRadius: "8px",
  cardBackground: "#e6faff",
  cardShadow: "0 2px 8px rgba(82,166,166,0.05)",
  navBackground: "#d3f6f6",
  navTextColor: "#1a3a3a",
  navLinkColor: "#52a6a6",
  navLinkHoverColor: "#2a6a6a",
  navLinkActiveColor: "#2a6a6a",
  navBorderColor: "#a3d6d6",
  headerBackground: "#e6faff",
  headerTextColor: "#1a3a3a",
  footerBackground: "#d3f6f6",
  footerTextColor: "#4a7c7c",
  buttonBackground: "#52a6a6",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#2a6a6a",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#1a3a3a",
  inputBorderColor: "#a3d6d6",
  linkColor: "#52a6a6",
  linkHoverColor: "#2a6a6a",
  linkHoverBackground: "#d3f6f6",
  listBackground: "#dbf9ff",
  listTextColor: "#1a3a3a",
  tableBackground: "#dbf9ff",
  tableHeaderBackground: "#d3f6f6",
  tableRowHoverBackground: "#a3d6d6",
  imageBorderColor: "#a3d6d6",
  imageHighlightColor: "#52a6a6",
  codeBackground: "#e6faff",
  codeTextColor: "#1a3a3a",
  scrollbarColor: "#52a6a6",
};
