import type { ITheme } from "../ITheme";

export const BlueTheme: ITheme = {
  name: "blue",
  bodyColor: "#eaf6fb",
  backgroundColor: "#f4faff",
  textColor: "#1a2a3a",
  altTextColor: "#3a4a5a",
  highlightColor: "#0056b3",
  borderColor: "#b3d1ea",
  borderRadius: "8px",
  cardBackground: "#eaf6fb",
  cardShadow: "0 2px 8px rgba(0,86,179,0.05)",
  navBackground: "#d0e6f6",
  navTextColor: "#1a2a3a",
  navLinkColor: "#0056b3",
  navLinkHoverColor: "#003366",
  navLinkActiveColor: "#003366",
  navBorderColor: "#b3d1ea",
  headerBackground: "#eaf6fb",
  headerTextColor: "#1a2a3a",
  footerBackground: "#d0e6f6",
  footerTextColor: "#3a4a5a",
  buttonBackground: "#0056b3",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#003366",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#1a2a3a",
  inputBorderColor: "#b3d1ea",
  linkColor: "#0056b3",
  linkHoverColor: "#003366",
  linkHoverBackground: "#d0e6f6",
  listBackground: "#f4faff",
  listTextColor: "#1a2a3a",
  tableBackground: "#f4faff",
  tableHeaderBackground: "#d0e6f6",
  tableRowHoverBackground: "#b3d1ea",
  imageBorderColor: "#b3d1ea",
  imageHighlightColor: "#0056b3",
  codeBackground: "#eaf6fb",
  codeTextColor: "#1a2a3a",
  scrollbarColor: "#0056b3",
};
