import type { ITheme } from "../ITheme";

export const BrownTheme: ITheme = {
  name: "brown",
  bodyColor: "#f7f3ef",
  backgroundColor: "#f5f0ea",
  textColor: "#4b3f2a",
  altTextColor: "#7c6a4a",
  highlightColor: "#a67c52",
  borderColor: "#d6c3a3",
  borderRadius: "8px",
  cardBackground: "#f7f3ef",
  cardShadow: "0 2px 8px rgba(166,124,82,0.05)",
  navBackground: "#e9e1d3",
  navTextColor: "#4b3f2a",
  navLinkColor: "#a67c52",
  navLinkHoverColor: "#7c6a4a",
  navLinkActiveColor: "#7c6a4a",
  navBorderColor: "#d6c3a3",
  headerBackground: "#f7f3ef",
  headerTextColor: "#4b3f2a",
  footerBackground: "#e9e1d3",
  footerTextColor: "#7c6a4a",
  buttonBackground: "#a67c52",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#7c6a4a",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#4b3f2a",
  inputBorderColor: "#d6c3a3",
  linkColor: "#a67c52",
  linkHoverColor: "#7c6a4a",
  linkHoverBackground: "#e9e1d3",
  listBackground: "#f5f0ea",
  listTextColor: "#4b3f2a",
  tableBackground: "#f5f0ea",
  tableHeaderBackground: "#e9e1d3",
  tableRowHoverBackground: "#d6c3a3",
  imageBorderColor: "#d6c3a3",
  imageHighlightColor: "#a67c52",
  codeBackground: "#f7f3ef",
  codeTextColor: "#4b3f2a",
  scrollbarColor: "#a67c52",
};
