import type { ITheme } from "../ITheme";

export const GoldTheme: ITheme = {
  name: "gold",
  bodyColor: "#fffbe6",
  backgroundColor: "#fff9db",
  textColor: "#3a2a1a",
  altTextColor: "#7c6a4a",
  highlightColor: "#ffd700",
  borderColor: "#ffe066",
  borderRadius: "8px",
  cardBackground: "#fffbe6",
  cardShadow: "0 2px 8px rgba(255,215,0,0.05)",
  navBackground: "#fff9db",
  navTextColor: "#3a2a1a",
  navLinkColor: "#ffd700",
  navLinkHoverColor: "#ccac00",
  navLinkActiveColor: "#ccac00",
  navBorderColor: "#ffe066",
  headerBackground: "#fffbe6",
  headerTextColor: "#3a2a1a",
  footerBackground: "#fff9db",
  footerTextColor: "#7c6a4a",
  buttonBackground: "#ffd700",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#ccac00",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#3a2a1a",
  inputBorderColor: "#ffe066",
  linkColor: "#ffd700",
  linkHoverColor: "#ccac00",
  linkHoverBackground: "#fff9db",
  listBackground: "#fff9db",
  listTextColor: "#3a2a1a",
  tableBackground: "#fff9db",
  tableHeaderBackground: "#fffbe6",
  tableRowHoverBackground: "#ffe066",
  imageBorderColor: "#ffe066",
  imageHighlightColor: "#ffd700",
  codeBackground: "#fffbe6",
  codeTextColor: "#3a2a1a",
  scrollbarColor: "#ffd700",
};
