import type { ITheme } from "../ITheme";

export const GrayTheme: ITheme = {
  name: "gray",
  bodyColor: "#f7f7f7",
  backgroundColor: "#ededed",
  textColor: "#222",
  altTextColor: "#555",
  highlightColor: "#888",
  borderColor: "#ccc",
  borderRadius: "8px",
  cardBackground: "#f7f7f7",
  cardShadow: "0 2px 8px rgba(136,136,136,0.05)",
  navBackground: "#ededed",
  navTextColor: "#222",
  navLinkColor: "#888",
  navLinkHoverColor: "#555",
  navLinkActiveColor: "#555",
  navBorderColor: "#ccc",
  headerBackground: "#f7f7f7",
  headerTextColor: "#222",
  footerBackground: "#ededed",
  footerTextColor: "#555",
  buttonBackground: "#888",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#555",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#222",
  inputBorderColor: "#ccc",
  linkColor: "#888",
  linkHoverColor: "#555",
  linkHoverBackground: "#ededed",
  listBackground: "#ededed",
  listTextColor: "#222",
  tableBackground: "#ededed",
  tableHeaderBackground: "#f7f7f7",
  tableRowHoverBackground: "#ccc",
  imageBorderColor: "#ccc",
  imageHighlightColor: "#888",
  codeBackground: "#f7f7f7",
  codeTextColor: "#222",
  scrollbarColor: "#888",
};
