import type { ITheme } from "../ITheme";

export const GreenTheme: ITheme = {
  name: "green",
  bodyColor: "#f6fff7",
  backgroundColor: "#e9fbe5",
  textColor: "#1a3a2a",
  altTextColor: "#4a7c6a",
  highlightColor: "#52a67c",
  borderColor: "#a3d6c3",
  borderRadius: "8px",
  cardBackground: "#f6fff7",
  cardShadow: "0 2px 8px rgba(82,166,124,0.05)",
  navBackground: "#d3e9e1",
  navTextColor: "#1a3a2a",
  navLinkColor: "#52a67c",
  navLinkHoverColor: "#2a6a4a",
  navLinkActiveColor: "#2a6a4a",
  navBorderColor: "#a3d6c3",
  headerBackground: "#f6fff7",
  headerTextColor: "#1a3a2a",
  footerBackground: "#d3e9e1",
  footerTextColor: "#4a7c6a",
  buttonBackground: "#52a67c",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#2a6a4a",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#1a3a2a",
  inputBorderColor: "#a3d6c3",
  linkColor: "#52a67c",
  linkHoverColor: "#2a6a4a",
  linkHoverBackground: "#d3e9e1",
  listBackground: "#e9fbe5",
  listTextColor: "#1a3a2a",
  tableBackground: "#e9fbe5",
  tableHeaderBackground: "#d3e9e1",
  tableRowHoverBackground: "#a3d6c3",
  imageBorderColor: "#a3d6c3",
  imageHighlightColor: "#52a67c",
  codeBackground: "#f6fff7",
  codeTextColor: "#1a3a2a",
  scrollbarColor: "#52a67c",
};
