import type { ITheme } from "../ITheme";

export const IndigoTheme: ITheme = {
  name: "indigo",
  bodyColor: "#f3f3fa",
  backgroundColor: "#e6e6fa",
  textColor: "#2a2a3a",
  altTextColor: "#4a4a7c",
  highlightColor: "#5252a6",
  borderColor: "#a3a3d6",
  borderRadius: "8px",
  cardBackground: "#f3f3fa",
  cardShadow: "0 2px 8px rgba(82,82,166,0.05)",
  navBackground: "#d3d3e9",
  navTextColor: "#2a2a3a",
  navLinkColor: "#5252a6",
  navLinkHoverColor: "#2a2a6a",
  navLinkActiveColor: "#2a2a6a",
  navBorderColor: "#a3a3d6",
  headerBackground: "#f3f3fa",
  headerTextColor: "#2a2a3a",
  footerBackground: "#d3d3e9",
  footerTextColor: "#4a4a7c",
  buttonBackground: "#5252a6",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#2a2a6a",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#2a2a3a",
  inputBorderColor: "#a3a3d6",
  linkColor: "#5252a6",
  linkHoverColor: "#2a2a6a",
  linkHoverBackground: "#d3d3e9",
  listBackground: "#e6e6fa",
  listTextColor: "#2a2a3a",
  tableBackground: "#e6e6fa",
  tableHeaderBackground: "#d3d3e9",
  tableRowHoverBackground: "#a3a3d6",
  imageBorderColor: "#a3a3d6",
  imageHighlightColor: "#5252a6",
  codeBackground: "#f3f3fa",
  codeTextColor: "#2a2a3a",
  scrollbarColor: "#5252a6",
};
