import type { ITheme } from "../ITheme";

export const LightTheme: ITheme = {
  name: "Light",
  bodyColor: "#f5f6fa",
  backgroundColor: "#ffffff",
  textColor: "#222",
  altTextColor: "#555",
  highlightColor: "#007bff",
  borderColor: "#e0e0e0",
  borderRadius: "8px",
  cardBackground: "#fafafa",
  cardShadow: "0 2px 8px rgba(0,0,0,0.05)",
  navBackground: "#f5f5f5",
  navTextColor: "#222",
  navLinkColor: "#007bff",
  navLinkHoverColor: "#0056b3",
  navLinkActiveColor: "#0056b3",
  navBorderColor: "#e0e0e0",
  headerBackground: "#f5f6fa",
  headerTextColor: "#222",
  footerBackground: "#f5f6fa",
  footerTextColor: "#555",
  buttonBackground: "#007bff",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#0056b3",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#222",
  inputBorderColor: "#e0e0e0",
  linkColor: "#007bff",
  linkHoverColor: "#0056b3",
  linkHoverBackground: "#e0e0ff",
  listBackground: "#fff",
  listTextColor: "#222",
  tableBackground: "#fff",
  tableHeaderBackground: "#f5f5f5",
  tableRowHoverBackground: "#e0e0ff",
  imageBorderColor: "#e0e0e0",
  imageHighlightColor: "#007bff",
  codeBackground: "#f5f5f5",
  codeTextColor: "#222",
  scrollbarColor: "#007bff",
};
