import type { ITheme } from "../ITheme";

export const OrangeTheme: ITheme = {
  name: "orange",
  bodyColor: "#fff8f3",
  backgroundColor: "#fff3e6",
  textColor: "#3a2a1a",
  altTextColor: "#7c6a4a",
  highlightColor: "#ffa652",
  borderColor: "#ffd6a3",
  borderRadius: "8px",
  cardBackground: "#fff8f3",
  cardShadow: "0 2px 8px rgba(255,166,82,0.05)",
  navBackground: "#ffe9d3",
  navTextColor: "#3a2a1a",
  navLinkColor: "#ffa652",
  navLinkHoverColor: "#cc8400",
  navLinkActiveColor: "#cc8400",
  navBorderColor: "#ffd6a3",
  headerBackground: "#fff8f3",
  headerTextColor: "#3a2a1a",
  footerBackground: "#ffe9d3",
  footerTextColor: "#7c6a4a",
  buttonBackground: "#ffa652",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#cc8400",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#3a2a1a",
  inputBorderColor: "#ffd6a3",
  linkColor: "#ffa652",
  linkHoverColor: "#cc8400",
  linkHoverBackground: "#ffe9d3",
  listBackground: "#fff3e6",
  listTextColor: "#3a2a1a",
  tableBackground: "#fff3e6",
  tableHeaderBackground: "#ffe9d3",
  tableRowHoverBackground: "#ffd6a3",
  imageBorderColor: "#ffd6a3",
  imageHighlightColor: "#ffa652",
  codeBackground: "#fff8f3",
  codeTextColor: "#3a2a1a",
  scrollbarColor: "#ffa652",
};
