import type { ITheme } from "../ITheme";

export const PurpleTheme: ITheme = {
  name: "purple",
  bodyColor: "#f5f3fa",
  backgroundColor: "#f8f6fc",
  textColor: "#3a2a4b",
  altTextColor: "#6a4a7c",
  highlightColor: "#7c52a6",
  borderColor: "#c3a3d6",
  borderRadius: "8px",
  cardBackground: "#f5f3fa",
  cardShadow: "0 2px 8px rgba(124,82,166,0.05)",
  navBackground: "#e1d3e9",
  navTextColor: "#3a2a4b",
  navLinkColor: "#7c52a6",
  navLinkHoverColor: "#4a2a6a",
  navLinkActiveColor: "#4a2a6a",
  navBorderColor: "#c3a3d6",
  headerBackground: "#f5f3fa",
  headerTextColor: "#3a2a4b",
  footerBackground: "#e1d3e9",
  footerTextColor: "#6a4a7c",
  buttonBackground: "#7c52a6",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#4a2a6a",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#3a2a4b",
  inputBorderColor: "#c3a3d6",
  linkColor: "#7c52a6",
  linkHoverColor: "#4a2a6a",
  linkHoverBackground: "#e1d3e9",
  listBackground: "#f8f6fc",
  listTextColor: "#3a2a4b",
  tableBackground: "#f8f6fc",
  tableHeaderBackground: "#e1d3e9",
  tableRowHoverBackground: "#c3a3d6",
  imageBorderColor: "#c3a3d6",
  imageHighlightColor: "#7c52a6",
  codeBackground: "#f5f3fa",
  codeTextColor: "#3a2a4b",
  scrollbarColor: "#7c52a6",
};
