import type { ITheme } from "../ITheme";

export const RedTheme: ITheme = {
  name: "red",
  bodyColor: "#fff6f6",
  backgroundColor: "#ffeaea",
  textColor: "#3a1a1a",
  altTextColor: "#7c4a4a",
  highlightColor: "#a65252",
  borderColor: "#d6a3a3",
  borderRadius: "8px",
  cardBackground: "#fff6f6",
  cardShadow: "0 2px 8px rgba(166,82,82,0.05)",
  navBackground: "#e9d3d3",
  navTextColor: "#3a1a1a",
  navLinkColor: "#a65252",
  navLinkHoverColor: "#6a2a2a",
  navLinkActiveColor: "#6a2a2a",
  navBorderColor: "#d6a3a3",
  headerBackground: "#fff6f6",
  headerTextColor: "#3a1a1a",
  footerBackground: "#e9d3d3",
  footerTextColor: "#7c4a4a",
  buttonBackground: "#a65252",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#6a2a2a",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#3a1a1a",
  inputBorderColor: "#d6a3a3",
  linkColor: "#a65252",
  linkHoverColor: "#6a2a2a",
  linkHoverBackground: "#e9d3d3",
  listBackground: "#ffeaea",
  listTextColor: "#3a1a1a",
  tableBackground: "#ffeaea",
  tableHeaderBackground: "#e9d3d3",
  tableRowHoverBackground: "#d6a3a3",
  imageBorderColor: "#d6a3a3",
  imageHighlightColor: "#a65252",
  codeBackground: "#fff6f6",
  codeTextColor: "#3a1a1a",
  scrollbarColor: "#a65252",
};
