import type { ITheme } from "../ITheme";

export const SteelTheme: ITheme = {
  name: "steel",
  bodyColor: "#f3f6fa",
  backgroundColor: "#e6eaf5",
  textColor: "#2a3a4b",
  altTextColor: "#4a6a7c",
  highlightColor: "#527ca6",
  borderColor: "#a3c3d6",
  borderRadius: "8px",
  cardBackground: "#f3f6fa",
  cardShadow: "0 2px 8px rgba(82,124,166,0.05)",
  navBackground: "#d3e1e9",
  navTextColor: "#2a3a4b",
  navLinkColor: "#527ca6",
  navLinkHoverColor: "#2a4a6a",
  navLinkActiveColor: "#2a4a6a",
  navBorderColor: "#a3c3d6",
  headerBackground: "#f3f6fa",
  headerTextColor: "#2a3a4b",
  footerBackground: "#d3e1e9",
  footerTextColor: "#4a6a7c",
  buttonBackground: "#527ca6",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#2a4a6a",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#2a3a4b",
  inputBorderColor: "#a3c3d6",
  linkColor: "#527ca6",
  linkHoverColor: "#2a4a6a",
  linkHoverBackground: "#d3e1e9",
  listBackground: "#e6eaf5",
  listTextColor: "#2a3a4b",
  tableBackground: "#e6eaf5",
  tableHeaderBackground: "#d3e1e9",
  tableRowHoverBackground: "#a3c3d6",
  imageBorderColor: "#a3c3d6",
  imageHighlightColor: "#527ca6",
  codeBackground: "#f3f6fa",
  codeTextColor: "#2a3a4b",
  scrollbarColor: "#527ca6",
};
