import type { ITheme } from "../ITheme";

export const YellowGreenTheme: ITheme = {
  name: "yellow-green",
  bodyColor: "#f7faf3",
  backgroundColor: "#f5fae6",
  textColor: "#3a4b2a",
  altTextColor: "#6a7c4a",
  highlightColor: "#a6c752",
  borderColor: "#d6eaa3",
  borderRadius: "8px",
  cardBackground: "#f7faf3",
  cardShadow: "0 2px 8px rgba(166,199,82,0.05)",
  navBackground: "#e9f6d3",
  navTextColor: "#3a4b2a",
  navLinkColor: "#a6c752",
  navLinkHoverColor: "#7c9c4a",
  navLinkActiveColor: "#7c9c4a",
  navBorderColor: "#d6eaa3",
  headerBackground: "#f7faf3",
  headerTextColor: "#3a4b2a",
  footerBackground: "#e9f6d3",
  footerTextColor: "#6a7c4a",
  buttonBackground: "#a6c752",
  buttonTextColor: "#fff",
  buttonHoverBackground: "#7c9c4a",
  buttonHoverTextColor: "#fff",
  inputBackground: "#fff",
  inputTextColor: "#3a4b2a",
  inputBorderColor: "#d6eaa3",
  linkColor: "#a6c752",
  linkHoverColor: "#7c9c4a",
  linkHoverBackground: "#e9f6d3",
  listBackground: "#f5fae6",
  listTextColor: "#3a4b2a",
  tableBackground: "#f5fae6",
  tableHeaderBackground: "#e9f6d3",
  tableRowHoverBackground: "#d6eaa3",
  imageBorderColor: "#d6eaa3",
  imageHighlightColor: "#a6c752",
  codeBackground: "#f7faf3",
  codeTextColor: "#3a4b2a",
  scrollbarColor: "#a6c752",
};
